### ISSUE TITLE
关于c++实现的智能合约 和 c++实现的项目 调用的问题

### ISSUE THREAD

**Issue by freelyyu** [uuosio/cplusplus-smart-contracts-programming#1]
你好，很抱歉打扰您，有一个问题想咨询您一下，我有一个用c++实现的项目，有一部分需要用到智能合约进行验证。看这个项目说可以用c++写智能合约，但是编译此类智能合约应该有单独的编译器。想问一下用c++写的项目可以和用c++写的智能合约有办法结合吗？ 现在的c++项目有办法调用c++实现的智能合约吗？

**Comment by ghost** [comment]
可以的，C++智能合约是基于eosio开源代码构建的区块链网络上运行的

编译C++智能合约代码的工具链是：https://github.com/eosio/eosio.cdt <https://github.com/eosio/eosio.cdt>

可以看下bilibili上我写的相关的教程，对于基于eosio的区块链的智能合约的基本原理有些概念，

https://www.bilibili.com/video/av54628632

视频是基于Python智能合约的，但是和C++的原理是一样的。

**Comment by freelyyu** [comment]
好的，谢谢！
